services:
  # Backend
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network

  # Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8081/api
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
