package com.tqs.backend;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class BDDHw1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }
  @Test
  public void bDDHw1() {
    // Test name: BDDHw1
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1920x1080 | 
    driver.manage().window().setSize(new Dimension(1920, 1080));
    // 3 | click | linkText=Cantinas | 
    driver.findElement(By.linkText("Cantinas")).click();
    // 4 | click | css=.text-lg | 
    driver.findElement(By.cssSelector(".text-lg")).click();
    // 5 | select | css=.text-lg | label=Cantina dos Barcos
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".text-lg"));
      dropdown.findElement(By.xpath("//option[. = 'Cantina dos Barcos']")).click();
    }
    // 6 | click | css=option:nth-child(2) | 
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    // 7 | click | css=.mb-6:nth-child(3) > .grid .inline-flex | 
    driver.findElement(By.cssSelector(".mb-6:nth-child(3) > .grid .inline-flex")).click();
    // 8 | click | css=.lucide | 
    driver.findElement(By.cssSelector(".lucide")).click();
    // 9 | click | css=.mb-6:nth-child(3) > .p-6 > .inline-flex | 
    driver.findElement(By.cssSelector(".mb-6:nth-child(3) > .p-6 > .inline-flex")).click();
    // 10 | click | css=.py-6:nth-child(1) | 
    driver.findElement(By.cssSelector(".py-6:nth-child(1)")).click();
    // 11 | click | css=.text-primary-foreground:nth-child(3) | 
    driver.findElement(By.cssSelector(".text-primary-foreground:nth-child(3)")).click();
    // 12 | click | css=.mb-6:nth-child(3) > .p-6 > .inline-flex | 
    driver.findElement(By.cssSelector(".mb-6:nth-child(3) > .p-6 > .inline-flex")).click();
    // 13 | mouseOver | css=.mb-6:nth-child(3) > .p-6 > .inline-flex | 
    {
      WebElement element = driver.findElement(By.cssSelector(".mb-6:nth-child(3) > .p-6 > .inline-flex"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 14 | mouseOut | css=.mb-6:nth-child(3) > .p-6 > .inline-flex | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 15 | click | css=.lucide | 
    driver.findElement(By.cssSelector(".lucide")).click();
    // 16 | click | css=.mb-6:nth-child(4) > .p-6 > .inline-flex | 
    driver.findElement(By.cssSelector(".mb-6:nth-child(4) > .p-6 > .inline-flex")).click();
    // 17 | mouseOver | css=.mb-6:nth-child(4) > .p-6 > .inline-flex | 
    {
      WebElement element = driver.findElement(By.cssSelector(".mb-6:nth-child(4) > .p-6 > .inline-flex"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 18 | mouseOut | css=.mb-6:nth-child(4) > .p-6 > .inline-flex | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 19 | click | css=.text-primary-foreground:nth-child(2) | 
    driver.findElement(By.cssSelector(".text-primary-foreground:nth-child(2)")).click();
    // 20 | click | css=.text-primary-foreground:nth-child(3) | 
    driver.findElement(By.cssSelector(".text-primary-foreground:nth-child(3)")).click();
    // 21 | click | linkText=Minhas Reservas | 
    driver.findElement(By.linkText("Minhas Reservas")).click();
    // 22 | click | css=.bg-white:nth-child(1) .inline-flex:nth-child(1) | 
    driver.findElement(By.cssSelector(".bg-white:nth-child(1) .inline-flex:nth-child(1)")).click();
    // 23 | click | css=.break-all | 
    driver.findElement(By.cssSelector(".break-all")).click();
    // 24 | click | css=.lucide | 
    driver.findElement(By.cssSelector(".lucide")).click();
    // 25 | click | css=.bg-white:nth-child(2) .inline-flex:nth-child(2) | 
    driver.findElement(By.cssSelector(".bg-white:nth-child(2) .inline-flex:nth-child(2)")).click();
    // 26 | click | css=.text-primary-foreground | 
    driver.findElement(By.cssSelector(".text-primary-foreground")).click();
    // 27 | click | css=span:nth-child(1) | 
    driver.findElement(By.cssSelector("span:nth-child(1)")).click();
    // 28 | click | css=.bg-transparent | 
    driver.findElement(By.cssSelector(".bg-transparent")).click();
    // 29 | type | css=.bg-transparent | 410ea59c-4542-40da-8c3f-af8aa89b60a0
    driver.findElement(By.cssSelector(".bg-transparent")).sendKeys("410ea59c-4542-40da-8c3f-af8aa89b60a0");
    // 30 | click | css=.inline-flex | 
    driver.findElement(By.cssSelector(".inline-flex")).click();
    // 31 | click | css=.rounded-md | 
    driver.findElement(By.cssSelector(".rounded-md")).click();
    // 32 | mouseOver | css=.rounded-md | 
    {
      WebElement element = driver.findElement(By.cssSelector(".rounded-md"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 33 | click | linkText=🍽️ Moliceiro | 
    driver.findElement(By.linkText("🍽️ Moliceiro")).click();
  }
}
